apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptobtg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptobtg
  template:
    metadata:
      labels:
        app: cryptobtg
    spec:
      containers:
      - name: cryptobtg
        image: cryptobtg:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cryptobtg-service
spec:
  type: LoadBalancer
  selector:
    app: cryptobtg
  ports:
  - port: 80
    targetPort: 80
